@startuml
'https://plantuml.com/sequence-diagram

header Message Bus
title Message Bus Sequence Diagram

autonumber

REFORGER -> RECOM: Authentication Request
REFORGER -> RECOM: Authentication Response
REFORGER -> RECOM: Another authentication Request
REFORGER <-- RECOM: another authentication Response


@enduml