@startuml
'https://plantuml.com/sequence-diagram

header Message Bus
title Message Bus Sequence Diagram

autonumber

REFORGER -> RECOM: Request Messages since {time}
REFORGER <-- RECOM: Response with latest messages after requested time
note right
Message List:
- Current Time
- Message Recipient
- Message Type
- Message Data
- Message Time
end note

REFORGER -> RECOM: Request Messages since {time}
REFORGER <-- RECOM: Response with latest messages after requested time

REFORGER -> RECOM: confirm message with UUID {uuid}



@enduml