@startuml
'https://plantuml.com/sequence-diagram

header Message Bus
title Create and Scan Map

autonumber

CLIENT -> SERVER: Authenticate
CLIENT <-- SERVER: Send Token
CLIENT -> SERVER: Map exists?
CLIENT <-- SERVER: Map does not exist
CLIENT -> SERVER: Create Map!
note right
Data:
 - mapName
 - dimensionXInMeter
 - dimensionYInMeter
 - dimensionZInMeter
 - oceanBaseHeight;
end note
SERVER -> SERVER: Create Map; persist
SERVER -> SERVER: Send in MessageBus: ScanMap-Chunk x/y
SERVER -> CLIENT: MessageBus: scan Map-Chunk
CLIENT -> CLIENT: Scan Chunk
CLIENT -> SERVER: Submit scanned Chunk

SERVER -> SERVER: Send in MessageBus: scan another Map-Chunk
SERVER -> SERVER: persist scanned Chunk
SERVER -> CLIENT: MessageBus: scan another Map-Chunk

...
...
...
...


CLIENT -> SERVER: Map exists?
note left
Alternate Flow:
 - map exists
 - trigger scan
end note
CLIENT <-- SERVER: Map does exist
CLIENT <-- SERVER: scan Map-Chunk x/y



@enduml