spring:
#  datasource:
#    url: asd
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        generate_statistics: true
#        format_sql: true
#        session:
#          events:
#            log:
#              LOG_QUERIES_SLOWER_THAN_MS: 200

logging:
  level:
      org:
        springframework:
          web:
            filter:
              CommonsRequestLoggingFilter: DEBUG
        #hibernate: DEBUG
        #SQL: DEBUG
        type:
          descriptor:
            sql:
              #BasicBinder: TRACE
#        vladmihalcea:
#          hibernate:
#            type:
#              util:
#                LogUtils: INFO

server:
  port: 8080
