#!/bin/sh

# Setup or starts a docker container with mariadb database; preconfigured for the application server
# Requirement: you need to have docker installed. Just execute the script for:
# - setup the container from zero
# - startup the container if it exists and it is not running yet
#
# Just run and done ...


# variables
MARIADB_CONTAINER_NAME="recom-mariadb"
MARIADB_PORT="8033"
MARIADB_DATA_DIRECTORY="db-datadir"
MARIADB_USER="recomUser"
MARIADB_PASSWORD="recomPwd"
MARIADB_ROOT_PASSWORD="recomRootPwd"
PROJECT_FOLDER=$(pwd)

docker pull mariadb

# Look if the docker db container already exists
DOCKER_DBCONTAINER_FILTER_STRING=$(docker container ls --all)
echo "$DOCKER_DBCONTAINER_FILTER_STRING"

if [[ $DOCKER_DBCONTAINER_FILTER_STRING == *"$MARIADB_CONTAINER_NAME"* ]]; then
  echo "Container $MARIADB_CONTAINER_NAME was found!"
  # start if exists
  echo "docker start $MARIADB_CONTAINER_NAME"
  docker start "$MARIADB_CONTAINER_NAME"
  # wait until db is startet and initialized
  sleep 10
  # run mariadb-docker-local cli, connected to running
  echo "Container $MARIADB_CONTAINER_NAME up and running!"
else
  # create container:
  echo "Container $MARIADB_CONTAINER_NAME is missing!"
  echo "... and create $MARIADB_CONTAINER_NAME DB!"

  mkdir -p "../$MARIADB_DATA_DIRECTORY"
  docker run -p $MARIADB_PORT:3306 -v $PROJECT_FOLDER/../$MARIADB_DATA_DIRECTORY:/var/lib/mysql -v $PROJECT_FOLDER/sql-init:/docker-entrypoint-initdb.d --detach --name $MARIADB_CONTAINER_NAME --env MARIADB_USER=$MARIADB_USER --env MARIADB_PASSWORD=$MARIADB_PASSWORD --env MARIADB_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD mariadb:latest
  docker start "$MARIADB_CONTAINER_NAME"
fi

# https://hub.docker.com/_/mariadb -> See "Initializing a fresh instance": you have to mount the init sql scripts to /docker-entrypoint-initdb.d