name: libs

on:
  push:
    branches: [ develop ]
    paths:
      - libs/**
      - libs/metrics/**
      - libs/security/**
      - .github/workflows/libs.yml

jobs:
  run:
    uses: ./.github/workflows/service-workflow.yml
    with:
      service: libs