name: recom-backend

on:
  push:
    branches: [ develop ]
    paths:
      - libs/**
      - services/recom-backend/**
      - .github/workflows/recom-backend.yml

jobs:
  run:
    uses: ./.github/workflows/service-workflow.yml
    with:
      service: recom-backend