name: recom-client

on:
  push:
    branches: [ develop ]
    paths:
      - libs/**
      - services/recom-client/**
      - .github/workflows/recom-client.yml

jobs:
  run:
    uses: ./.github/workflows/service-workflow.yml
    with:
      service: recom-client